chaos/pdsh

doc/pdsh.1.in

Noticed this English error in the manpage, dunno how "the list" got changed to "this" so long ago.  It's "the list" in other manpages.

Fix English error regarding hostranges in manpage

---

src/modules/torque.c

Some versions of torque will return server name as FQDN:PORT which ends up being in the JobID sent back to the pbs_server.

Fix for torque servername sometimes containing port

---

src/pdsh/opt.c

pdsh exports POSIXLY_CORRECT to child processes which affects the parameter parsing in applications run via pdsh. This code change ensures that POSIXLY_CORRECT is only exported to child processes if it was set in the pdsh environment at invocation.

Avoid exporting POSIXLY_CORRECT to child processes

---

doc/pdsh.1.in
src/pdsh/opt.c
tests/t0001-basic.sh

pdsh allows environment variables for various settings. However, the connect
and command timeouts only have command line options.
This change makes it so these timeouts can be specified as environment
variables. That way, if a site decides it is best, the variables can be
set to impact pdsh commands that are buried in infrastructure.
PDSH_CONNECT_TIMEOUT
and
PDSH_COMMAND_TIMEOUT
Are the environment variables.

pdsh timeouts can be set in environment variables

---

.travis.yml
src/common/hostlist.c
src/common/macros.h
src/modules/netgroup.c
src/pdsh/dsh.c
src/pdsh/mod.c
src/pdsh/opt.c
src/pdsh/wcoll.h
tests/t6036-long-output-lines.sh

This PR contains some fixes and cleanup for pdsh on Mac OSX.
There's still a problem building pdsh with genders support on osx, but other parts of pdsh build and are now being tested on the travis-ci osx builder.
Fixes #95

Fix pdsh build on MacOSX

---

src/pdsh/mod.c

Problem: Loading the slurm and nodeupdown modules wasn't working
with complaints about missing symbols from DSOs loaded by libslurm
and libnodeupdown. The assumption is that this is caused by symbols
in these libraries not having global scope since they were loaded
without RTLD_GLOBAL by pdsh dlopen(3).
This has been solved in the past by calling dlopen() with RTLD_GLOBAL
on these libraries in their respective modules instead of linking
to them directly. However, for now, it will be simpler to have
pdsh use RTLD_GLOBAL directly, since no issues are anticipated with
that approach.
If, in the future, the use of RTLD_GLOBAL causes issues, the alternate
fix can be used.
Fixes #98

add RTLD_GLOBAL to dlopen for modules

---

.travis.yml
configure.ac
src/common/pipecmd.c

Current travis builds of pdsh are failing because `CFLAGS=-Werror` was being set before `./configure` is run, and some configure checks, most notably the pthreads checks, are sensitive to `-Werror` and fail due to warnings. Move the `CFLAGS` setting to after `./configure` is run to resolve this issue. Also, pdsh `./configure` should fail if pthreads is not detected, so add a fatal error when pthreads is not detected, instead of delaying the error to link time.
I also tried to set up code coverage checks inside of travis-ci, however, this was for some reason causing intermittent failures of both the dshbak and pdcp tests. I think this is an artifact of the travis environment, but while trying to track it down I noticed that the error message generated in `pipecmd.c` when child processes …

travis-ci: fix failed builds and error messages from pipecmd

---

src/common/pipecmd.c

_pipecmd returns -1 on error, not 0 (since it's returning an fd). It may
in fact return 0 on success if stdin is closed, leading to a segfault.
This issue was discovered when running pdsh from a slurm suspend/resume program, where stdin is (inexplicably) closed.  However, it can be reproduced quite easily using `pdsh ... <&-`.
Presumably there's also a failure mode here where `_pipecmd` actually fails but this is not caught.

pipecmd: fix result check error handling

---

src/pdsh/dsh.c
tests/Makefile.am
tests/t6114-no-newline-corruption.sh

Fix the issue described in #114.
Turns out pdsh doesn't handle output without newlines too well, and output flush was reading from uninitialized memory for anything >= 8K bytes.
This PR also fixes arbitrary addition of newlines to output during the final flush.

fix output corruption with more than 8K bytes and no newline

---

NEWS
pdsh.spec
src/common/hostlist.c
src/modules/slurm.c
src/pdsh/dsh.c
src/pdsh/main.c

This PR includes some other minor fixes before we tag a 2.34 release.
Included are some simple fixes for issues found by lgtm.com scan, as well as a workaround for more recent Slurm inclusion of our list.h api in slurm.h.

minor fixes and enhancements for next release

---

doc/pdsh.1.in
src/modules/slurm.c
tests/t1003-slurm.sh

Like `srun -C`, this takes the produced hostlist and filters it to only SLURM nodes that have one of the specified features.  This is useful for us in combination with `-P`, but certainly open to other ideas.  One could imagine other slurm node filters as well, of course.  Does not accept the full slurm constraint syntax of `A&B|C` stuff, just a comma list that's essentially OR-d.

slurm: add -C to restrict hostlist to nodes with specified features

---

pdsh.spec

This file doesn't exist and causes rpmbuild to fail when the file can't be
found
I ran into this bug on the tagged 2.34 release

Remove README.QsNet from the RPM SPEC file's doc list

---

scripts/dshbak
tests/t5000-dshbak.sh

As described in #132 by @negregg, the fix for #70 inadvertently broke empty input in `dshbak`.
This PR adds a test to `t5000-dshbak.sh` to ensure empty input is handled by the script and then fixes the original fix.

dshbak: fix handling of empty input lines

---

.mergify.yml

Problem: When the mergify config was added to pdsh, important
conditions were left off of the rebase rules.
Add conditions for a required label, reviews, and title to
the mergify config.

mergify: fix missing conditions in mergify config

---

src/pdsh/Makefile.am

When building pdsh with slibtool (https://dev.midipix.org/cross/slibtool) it fails with many undefined references.
This is because of this command-line:
```
clang ../../src/common/.libs/libcommon.a main.o dsh.o mod.o rcmd.o opt.o 
privsep.o pcp_server.o pcp_client.o testcase.o wcoll.o cbuf.o config.o -O3 
-Wall -fno-strict-aliasing -ldl -s -pthread -o .libs/pdsh.inst -Wl,--export-dynamic
```
While with GNU libtool it works.
```
clang -O3 -Wall -fno-strict-aliasing -s -pthread -o pdsh.inst main.o dsh.o 
mod.o rcmd.o opt.o privsep.o pcp_server.o pcp_client.o testcase.o wcoll.o 
cbuf.o config.o -Wl,--export-dynamic  -ldl ../../src/common/.libs/libcommon.a -pthread
```
This is because by chance GNU libtool orders `../../src/common/.libs/libcommon.a` at the end while slibtool places it at the …

build: Use LDADD instead of LDFLAGS for libcommon.la.

---

src/modules/sshcmd.c

This patch is required to fix a testing issue with macos in PR #144 
Problem: On Darwin 20.6.0 hosts, sshcmd_signal() fails due to
the err() call which prints "sending SIGTERM to ssh" for an unkown
reason. However, this output is redundant with a similar log message
printed from pipecmd_signal(), so the message is probably useless.
Remove the problematic statement from sshcmd_signal().

sshcmd: fix sshcmd_signal on macos

---

.github/workflows/main.yml
src/modules/slurm.c

This PR fixes #152 and also includes some updates to CI configuration.

fix compile of slurm plugin against Slurm >= 23.x

---

src/modules/slurm.c
src/pdsh/mod.c
src/pdsh/opt.c

Since Slurm 20.11, slurm_init() needs to be called before any call to the Slurm API to make sure the config file is read in. We cannot call it in mod_slurm_init() or in mod_slurm_wcoll() directly as it requires slurm to be configured before use, thus pdsh would fail whenever the slurm plugin is found but Slurm is not configured correctly.

slurm: Call slurm_init() once before any call to Slurm API

---

NEWS

Problem: There are no release notes for pdsh-2.35.
Add release notes to the NEWS file.

NEWS: add release notes for pdsh-2.35

---

src/common/hostlist.c

Problem: Internally within the hostlist data structure, an array of hostranges is kept.  An out of bounds array access can occur if the number of hostranges is equal to the length of the array.
Add check to ensure out of bound array access is not allowed when iterating hosts.

common/hostlist: fix out of bounds array access

---

src/common/hostlist.c
src/common/hostlist.h

Problem: The pdsh copy of the hostlist code is slightly out of date with respect to "upstream" (the LLNL LSD-Tools repository).
Pull in the latest hostlist.[ch] from LSD-Tools (commit hash is in the comment header)

common/hostlist: update to latest from lsd-tools

---

src/common/macros.h

'true' and 'false' are proper keywords in C23.
This fixes issue #165.

Fix build on C23 compiler (gcc >= 15)

---

src/modules/mcmd.c
src/pdsh/cbuf.c

Compiling pdsh I get following warnings:
```
cbuf.c: In function ‘cbuf_write_line’:
cbuf.c:878:19: warning: ‘d’ may be used uninitialized [-Wmaybe-uninitialized]
878 |             ndrop += d;
|             ~~~~~~^~~~
cbuf.c:820:20: note: ‘d’ was declared here
820 |     int ndrop = 0, d;
|                    ^
mcmd.c: In function 'mcmd_init':
mcmd.c:211:9: warning: ignoring return value of 'setuid' declared with attribute 'warn_unused_result' [-Wunused-result]
211 |         setuid (getuid ());
|         ^~~~~~~~~~~~~~~~~~
mcmd.c: In function 'mcmd':
mcmd.c:280:5: warning: 'strncpy' output truncated before terminating nul copying 5 bytes from a string of the same length [-Wstringop-truncation]
280 |     strncpy (str, MRSH_LOCALHOST_KEY, MRSH_LOCALHOST_KEYLEN);
|     ^
mcmd.c:281:5: warning: …
```

Fix some compiler warnings when compiling pdsh
